# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 306382f4a5a5b1e963c8cbf4015102d4a10f2bf699de4b43c4dde05306e83f6dcda8c980a898488c9cbbf3f730b97c68001fc5c31bbf86830d983e76e53fd672

test:
  secret_key_base: b7f81717bab024fb67f7955addd7a5e6fe4f8c06fea24434b439a162e65c86c71902609be6261f2824ba7c50ec4a13cdad6a30684e1553a75cea8fcf86a04e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
